# Generated by Django 5.1.3 on 2024-11-07 00:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('application_number', models.CharField(max_length=20, unique=True)),
                ('date_of_birth', models.DateField()),
                ('student_phone', models.CharField(max_length=15)),
                ('parent_phone', models.CharField(max_length=15)),
                ('address', models.TextField()),
                ('qualification', models.CharField(max_length=100)),
                ('college', models.CharField(max_length=100)),
                ('cgpa', models.FloatField()),
                ('email', models.EmailField(max_length=254)),
                ('category', models.CharField(choices=[('General', 'General'), ('OBC', 'OBC'), ('SC/ST', 'SC/ST')], max_length=10)),
                ('seat_type', models.CharField(choices=[('NRI', 'NRI'), ('Non-IBS', 'Non-IBS')], max_length=10)),
                ('approved', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='InterviewScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interview_mark', models.IntegerField()),
                ('lbs_rank', models.IntegerField()),
                ('cgpa_degree', models.FloatField()),
                ('document_submission', models.BooleanField(default=False)),
                ('general_knowledge', models.IntegerField()),
                ('course_knowledge', models.IntegerField()),
                ('status', models.CharField(choices=[('Approved', 'Approved'), ('Rejected', 'Rejected')], max_length=10)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='portal.student')),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sslc', models.BooleanField(default=False)),
                ('entrance_admit_card', models.BooleanField(default=False)),
                ('payment', models.BooleanField(default=False)),
                ('allotment_menu', models.BooleanField(default=False)),
                ('hse', models.BooleanField(default=False)),
                ('lbs_admit_card', models.BooleanField(default=False)),
                ('degree', models.BooleanField(default=False)),
                ('school_leaving', models.BooleanField(default=False)),
                ('tc', models.BooleanField(default=False)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='portal.student')),
            ],
        ),
    ]
