# Generated by Django 5.1.3 on 2024-11-07 01:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='date_of_birth',
            new_name='dob',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='student_phone',
            new_name='phone_number',
        ),
        migrations.RemoveField(
            model_name='interviewscore',
            name='student',
        ),
        migrations.RemoveField(
            model_name='student',
            name='approved',
        ),
        migrations.AddField(
            model_name='interviewscore',
            name='application_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='interviewscore',
            name='cgpa_degree',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
        migrations.AlterField(
            model_name='interviewscore',
            name='document_submission',
            field=models.CharField(choices=[('submitted', 'Submitted'), ('not-submitted', 'Not Submitted')], max_length=20),
        ),
        migrations.AlterField(
            model_name='interviewscore',
            name='interview_mark',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='interviewscore',
            name='status',
            field=models.CharField(choices=[('approved', 'Approved'), ('rejected', 'Rejected')], max_length=10),
        ),
        migrations.AlterField(
            model_name='student',
            name='cgpa',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
        migrations.AlterField(
            model_name='student',
            name='qualification',
            field=models.CharField(max_length=50),
        ),
        migrations.CreateModel(
            name='StudentDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sslc', models.FileField(upload_to='documents/')),
                ('entrance_admit_card', models.FileField(upload_to='documents/')),
                ('payment', models.FileField(upload_to='documents/')),
                ('allotment_menu', models.FileField(upload_to='documents/')),
                ('hse', models.FileField(upload_to='documents/')),
                ('lbs_admit_card', models.FileField(upload_to='documents/')),
                ('degree', models.FileField(upload_to='documents/')),
                ('school_leaving', models.FileField(upload_to='documents/')),
                ('tc', models.FileField(upload_to='documents/')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='portal.student')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('faculty', 'Faculty')], default='faculty', max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Document',
        ),
    ]
